version: "3.9"

services: 
  db:
    build: .
    image: postgres
    container_name: postgres
    networks:
      - network
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql
    ports: 
      - "5440:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    networks: 
      - network

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: "vinigbatista21@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports: 
      - "15432:80"
    depends_on: 
      - db
    networks: 
      - network

  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
      - "8000:8000"
    depends_on: 
      - db
    links: 
      - db:db
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres-data:
    external: true